### ISSUE TITLE
无法在 Slimefun4 汉化 canary 版中正常使用

### ISSUE THREAD

**Issue by XIAYM-gh** [SlimefunGuguProject/ExtraHeads#3]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExtraHeads/issues)，且没有找到相同的问题

### 问题描述

如题，在sf 汉化canary版中估计没有1.14支持
加载后报了一个 NoSuchFieldError
打开头颅列表也只到巨人 （即1.14-）

换回 2022.12 rel 之后又正常工作

### 复现步骤

1. 安装最新的 Slimefun4 汉化构建版
2. 安装本插件最新构建版和 Lib

### 预期行为

在Canary版 SF4 中也能包含1.14+的头颅

### 服务器日志

请见 "错误报告"

### 错误报告

https://paste.guizhanss.net/notunaxajo.properties

### 服务端软件

Purpur

### Minecraft 版本

1.19.3

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

d001522-canary
即上周提交的最新版

### 插件版本

6

**Comment by XIAYM-gh** [comment]
服务器版本为 Purpur 1.19.3
Java版本为 17.0.5 OpenJ9
日志待会上传

**Comment by XIAYM-gh** [comment]
或许我稍后可以提交一个PR

**Comment by ybw0014** [comment]
上游扔了修复了，下游忘记修了。今天上完课有空再修
